### ISSUE TITLE
configuring order of serial port detection / assignment

### ISSUE THREAD

**Issue by feilipu** [wwarthen/RomWBW#192]
I would like to be able to modify the order of the assignments for the serial ports, by configuration.

The use case is to have [an ACIA serial port emulation (providing a keyboard/VGA interface)](https://github.com/feilipu/ux_module) appearing first as the boot console that a human can type into, and have additional serial ports appearing as later units.

The current boot message (after tweaking noted below) looks like this.

```sh
RomWBW HBIOS v3.1.1-pre.43, 2021-02-11

RC2014 Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1, Z2 MMU
512KB ROM, 512KB RAM

ACIA0: IO=0x40 ACIA MODE=115200,8,N,1
SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ACIA0:      RS-232            115200,8,N,1
Char 1      SIO0:       RS-232            115200,8,N,1
Char 2      SIO1:       RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          256KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA


RC2014 Boot Loader

Boot [H=Help]:
```
I get this after manually tweaking the ACIA/SIO order in `hbios.asm` in three places.
[Line 1615](https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/hbios.asm#L1615)
[Line 1649](https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/hbios.asm#L1649)
[Line  2772](https://github.com/wwarthen/RomWBW/blob/master/Source/HBIOS/hbios.asm#L2972)

Is there an easier / better way to get this outcome?
Perhaps there could be a "BOOT_CONSOLE" configuration created somewhere?

**Comment by wwarthen** [comment]
Well, there is an equate called "FORCECON" that Phillip Summers (@b1ackmai1er) implemented that does exactly what you propose.  This setting does not appear in the official config files, but can be added there with a .SET line.

The only thing that is a bit funky about this approach is that it is very dependent on the exact configuration.  Any changes that enable or disable serial devices will change the device table and may render the FORCECON setting invalid.  However, it you leave things alone, it should work fine.

I have looked at this issue a few times because it is a common request.  I was never able to come up with a clean solution.  If you see a better approach, let me know.

Thanks,

Wayne

**Comment by feilipu** [comment]
That will do nicely. Case closed.
