### ISSUE TITLE
v3.0.1 Hangs before boot loader prompt

### ISSUE THREAD

**Issue by anjennings** [wwarthen/RomWBW#302]
Hi, I'm trying to bring up a system on a custom Z180 based board and I'm running into this issue:

```
RomWBW HBIOS v3.0.1, 2022-08-13

TOM80 Z8S180-N @ 18.432MHz IO=0x00
1 MEM W/S, 2 I/O W/S, INT MODE 2
512KB ROM, 512KB RAM

ASCI0: IO=0x00 ASCI W/BRG MODE=115200,8,N,1
ASCI1: IO=0x01 ASCI W/BRG MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=384KB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            115200,8,N,1
Char 1      ASCI1:      RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          384KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA

*hangs*
```

At this point the system either hangs if in INT mode 2 or halts in INT mode 0 and no boot prompt appears.

Nearly all peripherals are disabled aside from ASCI and Memory Disk drivers.  I've tried using rom images for systems with comparable hardware and I get the same or similar results.  Is this a sign of a hardware problem or some other known issue?

Any help is appreciated, thanks.

**Comment by wwarthen** [comment]
Hi Aidan,

I will be happy to do what I can.  It appears you have figured out how to build a custom ROM and successfully program it.  I don't have much time right now, but as a first step, would you try downloading the dev branch code and building from that?  The dev branch startup is a little more robust in a few areas.  It would be interesting to see what your results are with that code.

If that does not help, then I will help you add some debugging code to try and figure this out.

Thanks,

Wayne

**Comment by anjennings** [comment]
Hi Wayne,

Thanks for the quick reply!  Rebuilding in the dev branch yields similar results:

```
RomWBW HBIOS v3.1.1-pre.183, 2022-08-14

Tom80 [TOM80_std] Z8S180-N @ 18.432MHz IO=0x00
3 MEM W/S, 4 I/O W/S, Z180 MMU
512KB ROM, 512KB RAM
ROM VERIFY: 00 00 00 00 PASS

ASCI0: IO=0x00 ASCI W/BRG MODE=115200,8,N,1
ASCI1: IO=0x01 ASCI W/BRG MODE=115200,8,N,1
MD: UNITS=2 ROMDISK=384KB RAMDISK=256KB

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      ASCI0:      RS-232            115200,8,N,1
Char 1      ASCI1:      RS-232            115200,8,N,1
Disk 0      MD0:        RAM Disk          256KB,LBA
Disk 1      MD1:        ROM Disk          384KB,LBA

*hangs*
```

INT Mode 0 & 2 Halt and INT Mode 1 just hangs without halting.

Where in the code would be a good place to start debugging?

**Comment by wwarthen** [comment]
This is an odd place for the boot to hang.  At this point, you have already exercised the bank switching and the HBIOS has been transitioned to a RAM bank.  This essentially proves out all of your basic hardware.

It appears that your boot is failing just before making the transition to the boot loader.  The boot loader is a separately assembled module that is loaded by HBIOS at the very end of the boot process.  You can take a look at hbios.asm in the HBIOS directory.  It is a big file, but search for the INITSYS3: label.  You will see that it calls PRTSUM which is working because that is what prints the device summary which is the last thing you see.  Now skip down to INITSYS4: and you will see the code that chains to the boot loader.

Are you comfortable with Z80 assembler?  If so, you just want to add some diagnostics to see how far you are getting.  I typically use something like the following to display progress:

```
        PUSH    AF
        LD      A,'1'
        CALL    COUT
        POP     AF
```

You can use other characters than '1' to use multiple of these.

You probably want to add something right before the "CHAIN TO BOOTLOADER..." work to make sure you are getting there.  You will see the code then uses a fancy routine called HBX_BNKCALL.  This swaps the lower 32K to the selected bank and then calls the specified address.  The big question is whether it gets there or not.  To determine this, you can add a progress display to the start of romldr.asm.  Because romldr relocates itself at startup, you cannot add any code until after the relocation  You can add a progress display after the startup: label, but do it after the first line that sets the stack.

A couple of notes.  For now, I suggest you use INTMODE 0.  This will just keep interrupts out of the picture until the problem is found.  Second, I note that you are running the Z180 at I/O address $00.  That should be fine, but is not done on any of the existing platforms, so perhaps there is a code issue related to that.  For now, I recommend placing it at $C0.

If you are uncomfortable adding the progress display code or if you run into trouble doing it, let me know.  I will create a version of the code that includes some of this.  It just takes more time if you need to wait for me yo add debug code for every cycle we go through.

Finally, let me just speculate on what the problem could be.  There are really two basic possibilities that I see.  First, there is a problem with the romldr code such that it is either corrupt or not being loaded into the target bank as expected.  Second, something has happened to the 512 byte area at the top of RAM ($FE00-$FFFF) where the bank switching and bank copying routines live.

Let me know if this is of any help or if you would like me to create some diagnostic code.

Oh, I have a question for you.  Do you have anything like indicator LED(s) that can be turned on/off in code?  Frequently this is better for debugging.

Thanks,

Wayne

**Comment by anjennings** [comment]
This has been a big help, thank you again.

I added 4 checks to HBIOS.asm and can confirm that execution gets to the ```CALL HBX_BNKCALL```. 
I added a 5th check to romldr.asm which I never saw.

romldr.asm:
```
;
	.ORG	$8000 + $
;
start:
	ld	sp,bl_stack		; setup private stack

	PUSH    AF
        LD      A,'5'
        CALL    COUT
        POP     AF
	
	call	delay_init		; init delay functions
```
I tried putting a check in the HBX_BNKCALL routine but that seemed to cause it to return back to INITSYS4, and therefore, halt.  Removing these checks made it not return to INITSYS4.  I can usually make sense of Z80 asm but this left me puzzled.  I'm not sure what state the stack is in when this is called or what calling COUT might do so I'm at a loss, maybe you can explain.  It does seem like this is what's causing the issue however.

I did change the IOBASE and INTMODE as you suggested.  I do not have a dedicated programable LED, I only have HALT and M1 signals on my board which I've used to debug thus far when serial was not available.

**Comment by wwarthen** [comment]
> I added 4 checks to HBIOS.asm and can confirm that execution gets to the `CALL HBX_BNKCALL`. I added a 5th check to romldr.asm which I never saw.

I guess this is not surprising.  It is consistent with my guesses about the problem area.  It probably means that something has gone wrong with either the romldr code or the 512 byte HBIOS proxy code.

> I tried putting a check in the HBX_BNKCALL routine but that seemed to cause it to return back to INITSYS4, and therefore, halt. Removing these checks made it not return to INITSYS4. I can usually make sense of Z80 asm but this left me puzzled. I'm not sure what state the stack is in when this is called or what calling COUT might do so I'm at a loss, maybe you can explain. It does seem like this is what's causing the issue however.

This is where things get ugly.  Since BNKCALL swaps out the bank that contains the COUT code, it is difficult to track through the execution of BNKCALL.  However, if you added the progress tracking code to the very beginning of BNKCALL, then you should have at least seen the number displayed.  Is that where you added the code?  If so and you never saw the number displayed, then I suspect the upper 512 bye HBIOS proxy has been corrupted somehow.  Can you confirm what you did?

> I did change the IOBASE and INTMODE as you suggested. I do not have a dedicated programable LED, I only have HALT and M1 signals on my board which I've used to debug thus far when serial was not available.

OK.

-Wayne

**Comment by anjennings** [comment]
> However, if you added the progress tracking code to the very beginning of BNKCALL, then you should have at least seen the number displayed. Is that where you added the code?

That was my mistake, I added it towards the end.  Adding checks at the start confirms that execution gets to at least the ```HBX_BNKCALL3``` label.  Does this suggest that the error is probably with the romldr then?

-Aidan

**Comment by wwarthen** [comment]
I don't see how there could be a problem with the romldr code itself since it is known working code on a wide variety of systems.  It does suggest that there is some kind of problem with either 1) loading of the romldr into the RAM bank it runs from or 2) some kind of problem with bank switching.

All of this surprises me because prior to your system hanging, it has already performed a copy of the HBIOS code from ROM to RAM and successfully transitioned to running in RAM.  In fact, you may notice that BNKCALL is used to perform that process, so it worked initially.

Is there anything creative going on in your systems memory layout?  RomWBW is expecting the lower 512KB of physical memory to be the ROM and the second 512KB of physical memory to be the RAM.  Another way to say it is that A19 should determine whether RAM or ROM is accessed.  If A19 is high, RAM should be accessed.  If low, ROM should be accessed.

This is looking like a pretty subtle problem and I'm sure it is somehow related a hardware difference between your system and a generic RC2014 Z180 system.  I just don't see what it might be yet.  Let me know about your physical memory layout and I will give some more thought to how to track this down.

Thanks,

Wayne

**Comment by anjennings** [comment]
The system's memory map is just your standard SST39SF040 ROM in low memory and AS6C4008 RAM in high.  Address and signal decoding is handled via a GAL16V8 chip which I have double checked the logic on.  I'll re-flash it when I have the chance just to be sure.

Just a thought I had: do you know of any utilities that would verify that the ram is functioning at every address?  Its a surface mount chip so I can't just stick it in a breadboard unfortunately.  If none exists I can always write one myself just to confirm that isn't the issue.

Thanks,
-Aidan

**Comment by wwarthen** [comment]
> The system's memory map is just your standard SST39SF040 ROM in low memory and AS6C4008 RAM in high. Address and signal decoding is handled via a GAL16V8 chip which I have double checked the logic on. I'll re-flash it when I have the chance just to be sure.

OK, that sounds very normal.

> Just a thought I had: do you know of any utilities that would verify that the ram is functioning at every address? Its a surface mount chip so I can't just stick it in a breadboard unfortunately. If none exists I can always write one myself just to confirm that isn't the issue.

Not that I know of.  But... you jogged my memory that there is some test code in HBIOS that dynamically determines the size of the RAM available by probing bank-by-bank.  The routine places unique seed values in each bank as it counts to ensure that each bank counted is operating independently of the others (no wraparound, etc.).

Add a #DEFINE of TESTING near the top of hbios.asm to enable this test code:

```
...
#INCLUDE "std.asm"
;
#DEFINE	HBIOS
;
#DEFINE TESTING
...
```

Boot with the updated ROM and you will see a line like this:

`512KB ROM, 512KB RAM, RAMBANKS=0x10, RTCDEF=0x00`

The `RAMBANKS` value is what we care about.  If it is anything other than 0x10, then there is a RAM bank mapping issue of some kind.

The code does not do an actual RAM test of the bytes in the RAM bank, but you could potentially expand the functionality of the routine to do this.

Thanks,

Wayne

**Comment by b1ackmai1er** [comment]
Hi - Would Andrews ramtest program help?
https://github.com/wwarthen/RomWBW/tree/dev/Source/Apps/Test/ramtest

**Comment by wwarthen** [comment]
> Hi - Would Andrews ramtest program help? https://github.com/wwarthen/RomWBW/tree/dev/Source/Apps/Test/ramtest

It's a good suggestion @b1ackmai1er .

I actually did consider this option, but. I see a couple problems.  First, it runs as a CP/M application and at the moment @anjennings is unable to get to a CP/M prompt (or even the debug monitor).  Second, the program is very specific to the MBC bank switching (it manipulates the bank switching registers directly) and Aidan is using the Z180's native bank switching which is a completely different animal.

There may be some code in the application that could be repurposed, but it build be a substantial amount of work.

Thanks,

Wayne

**Comment by anjennings** [comment]
I think I've got things working (kinda).

I re-flashed my GAL chip with slightly different code which got execution to at least romldr but it was still failing.  After couple of resets it started getting to the boot prompt, and now it seems to be working.  I can't say _exactly_ what exactly was causing the issue but whatever it was, it was hardware related.  Probably a combination of a poor connection between the ROM, the ZIF Socket, and the DIP socket on the board and/or the GAL chip and its logic.

For the record, I did clean the board with isopropyl alcohol after assembly but I'm not at my workshop right now so I'll go buy some from the store when I've got a chance and give it another cleaning just to be sure.

Thank you for all your help with debugging!  I am looking forward to all the fun I'm going to have with this system.
