### ISSUE TITLE
Zeta2 - FD not being detected after upgrade from v3.0.1 to v3.2.0

### ISSUE THREAD

**Issue by robosnacks** [wwarthen/RomWBW#339]
Hi, I've found an issue with the FD no longer being detected on my Zeta2 after upgrading to v3.2.0

I note the expected IO address is different - the problem I guess...
On v3.0.1: `FD: IO=0x30 UNITS=2`
On v3.2.0: `FD: MODE=ZETA IO=0x36 NOT PRESENT`
I can however still manipulate a disk with FDU with no apparent problem.

The new Xmodem Flash Updater got me painlessly back to v3.0.1 in any case. 👍 

Attached is a TeraTerm log to illustrate, showing a FLASH WRITE from FD0: to upgrade from v3.0.1 to v3.2.0
[teraterm.log](https://github.com/wwarthen/RomWBW/files/11214555/teraterm.log)

**Comment by wwarthen** [comment]
Thanks for the bug report @robosnacks.  Well documented!

Turns out this was reported by another user as well.  A fix is already in place in the v3.2.1 Release Candidate which is available on the [Releases](https://github.com/wwarthen/RomWBW/releases) page.  The Release Candidate is pretty safe to try because there have been only a few small changes.  Alternatively, I plan to finalize v3.2.1 this weekend and you could wait for that.

Sorry for the trouble.  I am going to close this issue now because the fix is complete.  If you find that you still have problems after trying v3.2.1, please reopen this issue.

Thanks!

Wayne

**Comment by robosnacks** [comment]
No trouble at all. Just tried v3.2.1rc3 and it's working great. Thanks for RomWBW, I really enjoy using it!

**Comment by wwarthen** [comment]
Cool.  Thanks for confirming it works.
