### ISSUE TITLE
I am working on Linux. Since Version 3.2.0 it is no longer working. First Problem is with zxcc. I am getting an error msg zxcc: Cannot locate bios.bin If I change to this path and do a make twice, it works. Second problem is it no longer generates die ROM-Images. It stops in HBIOS and asks for the he platform. I think there is a problem in the Build.sh which should call itself in a loop, but that doesn't work.

### ISSUE THREAD

**Issue by hjkit** [wwarthen/RomWBW#373]

**Comment by wwarthen** [comment]
Hi @hjkit,

The distribution builds of RomWBW are all produced by an automated Linux build on GitHub.  So, we just need to figure out why it is not working on your system.

Make sure you do a "make clean" in the top level directory before running a build.

I need some more information.

- What distribution and version of Linux are you using?
- Please post the exact command line you use to start the build.
- Please post a full log of your failing build.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Hi @hjkit,

Thank you for the additional information.  It was very helpful.

In order to generate a log file when running make, you need to pipe the output to a file.  For example:

`make >make.log 2>&1`

The change to `zxcc.c` was a bug fix that only impacted a few versions of Linux.  It appears that this bug **does** affect your version of Linux.  By applying the fix to the older versions of RomWBW, the build got past that problem.  That is a good.  However, I recommend that you use the development branch (e.g., v3.4.0-dev.XX) to avoid this problem.  The development branch is reliable at this point.

When you run `make` without any parameters, the normal behavior is to prompt you to enter the platform and subsequently the configuration you want to build.  It looks like this is what is happening and that is where the build stops (which is normal).  At that point you just need to enter the platform and the build will continue.

To avoid getting the prompts, you can pass parameters to `make` to specify the platform and configuration.  For example, the following command will build the RCZ80 platform using the std configuration without prompting:

`make ROM_PLATFORM=RCZ80 ROM_CONFIG=std`

If your desire is to build all of the ROMs as in a full distribution build, you can use this command:

`make dist`

Thanks,

Wayne

**Comment by wwarthen** [comment]
Hi @hjkit,

I am checking on the status of this issue.  Are you able to complete the build process OK now

Thanks,

Wayne

**Comment by wwarthen** [comment]
I am going to close this issue due to lack of activity.  @hjkit, please reopen this issue if necessary.

Thanks,

Wayne
