### ISSUE TITLE
XMODEM issue with RC130 and versions after 3.0.1

### ISSUE THREAD

**Issue by famousmoose** [wwarthen/RomWBW#375]
I have a Z180 based rc130 SBC. with 3.0.1 the XM command works as expected with picocom and sz to receive files via X/YModem.

With 3.2.1 I get the following when doing a transfer (output below is from sz I assume):

Ymodem sectors/kbytes sent:   0/ 0kRetry 0: Got 4b for sector ACK
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: NAK on sector
Retry 0: Retry Count Exceeded

This seems to be associated with the creation of the 'new' xm, possibly somewhere around commit 717ce95. xmold.com from v3.2.1 seems to work better, starting transfers and completing in some cases, but in others reproducibly failing with:
Ymodem sectors/kbytes sent:   0/ 0kRetry 0: Got 4b for sector ACK
Retry 0: NAK on sector
Ymodem sectors/kbytes sent: 1895/236kRetry 0: No ACK on EOT

Transfer incomplete

*** exit status: 128 ***

**Comment by wwarthen** [comment]
Hi @famousmoose,

I suspect this is happening because flow control is not enabled somewhere in the serial channel you are using for the file transfer.  RomWBW does enable flow control in the SC131.  Can you check that you have hardware flow control (rtscts) enabled in picocom?  It is also possible that your serial-TTL adapter is not passing flow control, but this is less likely.

In general, 115200 baud is too fast for RomWBW to keep up without inbound flow control.  It turns out that a Z180 at 18 MHz "sometimes" worked in the past.  The Z180 was just barely fast enough depending on how your system was configured.

There have been a few changes in RomWBW over the last few releases that have added a bit of overhead to serial processing.  I think these have pushed you over the edge.  Yes, one of the changes was in the XM.COM application itself.  It was modified to handle serial ports via an API instead of direct to hardware.  This was necessary due to the ever increasing number of serial port hardware variants being supported.  However, it had the unfortunate side effect of impacting serial port servicing overhead.  In your case XMOLD.COM helped, but it was still unreliable because you are on the edge.

Please attempt to enable flow control and let me know how it goes.

Thanks,

Wayne

**Comment by famousmoose** [comment]
Hardware flow control has indeed fixed the issue. Thanks for the detailed explanation.
