### ISSUE TITLE
Where to modify number of drives/slices for SD card

### ISSUE THREAD

**Issue by MockbaTheBorg** [wwarthen/RomWBW#381]
Hi Wayne,

Happy new year.
Not really a defect issue, just a general question.
I have built RomWBW with PPISD support (just a SD card patched onto the Zeta2 parallel connector) and I see it gave me 8x8Mb drives.
However, the card I have in there is 256M, so I should be able to have 5 more drives, until the limit of P:.
I have been searching around the source code for a configuration of number of drives available. However I have not easily found it.
Maybe I have just overlooked it, not sure, as I believe it should be something easy to find somewhere.
Maybe you can point me to the right direction?

Thanks,
Marcelo.

**Comment by wwarthen** [comment]
Hi Marcelo,

The assignment of the drive letters when an OS starts is based on an algorithm that depends on the number of disk drives in the system.  This is basically documented in the User Guide in section "4.1.1 Default Drive Letter Assignment".

Configuration options for this algorithm are not provided because it is far easier to just use the `ASSIGN` command to customize your drive letters.  If you want specific drive letters to always be assigned at boot, just create an auto-submit batch file.  For most of the OSes, this file would be called `PROFILE.SUB`.  This approach allows:

- Customization of the drive letters without creating a custom ROM
- Different drive letter customization depending on the drive you select to boot from
- Easy on-the-fly reconfiguration of the drive letters

Let me know if this addresses your need.

Thanks,

Wayne

**Comment by MockbaTheBorg** [comment]
Perfect ... this is pretty cool. I have tried here, including the ASSIGN command and it all works.
Thank you so much.

**Comment by wwarthen** [comment]
Very happy this is working for you.
