### ISSUE TITLE
DiskList.txt is missing from the Binary directory

### ISSUE THREAD

**Issue by shawnshekari** [wwarthen/RomWBW#390]
ReadMe.txt references DiskList.txt but that file is missing.

I saw in a discussion that there was an effort to document the disks in each folder with a ReadMe.txt so perhaps the single DiskList.txt is being discontinued.  If that is the case the ReadMe.txt in the Binary directory should be updated.

"Documentation of the pre-built disk images is contained in the DiskList.txt file in this directory."

Happy to help if you point me in the correct direction.

Thank you for RomWBW!

-Shawn

RC2014 Pro

SC140/SC125/SC144
Current preferred custom combo: copy /B hd1k_prefix.dat + hd1k_nzcom.img + hd1k_hitechc.img + hd1k_tpascal.img + hd1k_games.img shawn.img

SC792 system on the way

**Comment by shawnshekari** [comment]
And now I have found "RomWBW Disk Catalog.pdf" in the Doc directory so perhaps that is the file ReadMe.txt in Binary should reference.

**Comment by wwarthen** [comment]
Thank you for reporting this @shawnshekari.

Yes, the reference to DiskList.txt in the Binary directory is obsolete and I will correct that.  I will push an update shortly.  The contents of that file were integrated into  the RomWBW User Guide.

DiskList.txt just generally enumerated the disk images -- not the actual contents in detail.  The RomWBW Disk Catalog document was an excellent effort to document the full contents (at the file level) of all disk images.  Unfortunately, it has become out-of-date over time.  It is incredibly hard to maintain because of the way that files are merged from multiple sources to generate the final disk images.  I started to utilize the ReadMe.txt files in the disk image source directories (e.g., `d_zsdos`) to document the contents.  However, that is also not complete or accurate at this point.

I am open to suggestions on how to keep the disk content documentation up-to-date.

Thanks,

Wayne

**Comment by shawnshekari** [comment]
I wish I had a clever suggestion like utilizing Doxygen somehow, I will put some thought into it and start a discussion if I have any ideas.

Thank you again for all the great work!

**Comment by wwarthen** [comment]
I have posted the correction, so I am going to go ahead and close this issue.

Something like Doxygen is exactly what I have in mind, but there is no source code to work from.  If you come up with a great idea, let me know.

Thanks,

Wayne
