### ISSUE TITLE
How to modify the ROMDISK image

### ISSUE THREAD

**Issue by z80micro-mc** [wwarthen/RomWBW#394]
I can move files to / from the SD drives.

How do I modify / create a custom ROMDISK?

There would not appear to be a tool to manipulate the ROMDISK image to add / delete files.

I am quite happy once I have a ROMDSK image file in programming it into EEPROM, though I do note that FLASH only appears to work in quanta of 32 KB. As far as I can see from the datasheet the flash chip works in 4 KB blocks.

Thanks 

Peter

**Comment by wwarthen** [comment]
Hi @z80micro-mc,

> How do I modify / create a custom ROMDISK?
> There would not appear to be a tool to manipulate the ROMDISK image to add / delete files.

RomWBW creates the ROM disk images as part of the build process.  The contents of the ROM disks is found in the distribution in the Source/RomDsk folder.  You will find several sub-folders (ROM_xxxKB).  These sub-folders contain the raw files that will be placed in the ROM disk during the ROM build.  There is 128K of other stuff on the ROM chip, so the ROM disk size will be the size of your ROM chip less 128K.  So, for the typical 512K ROM chip, you will have a 384K ROM disk.  So, in that case, you would look in the ROM_384KB sub-folder.  You can add/delete/replace the files in this sub-folder, then build a new ROM which will contain the files you have chosen.  I don't know if you are familiar with building a new ROM, but the instructions are in Source/ReadMe.txt.

> I am quite happy once I have a ROMDSK image file in programming it into EEPROM, though I do note that FLASH only appears > to work in quanta of 32 KB. As far as I can see from the datasheet the flash chip works in 4 KB blocks.

Yes, once you have built your new ROM image, you will need to program it.  I am not the author of the FLASH program, but it is possible that it is forcing 32K blocks because RomWBW operates with a fixed bank size of 32K.  Normally, you would reprogram the entire ROM chip.  If you wanted to program just the ROM disk portion of the chip, you would need to start the programming at 128K.  I don't know if the FLASH utility will do that.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Hi @z80micro-mc,

I'm going to go ahead and close this since I have not heard anything further.  Please feel free to reopen if you need anything else.

Thanks,

Wayne
