### ISSUE TITLE
CBIOS Issue with High slice numbers in hd512

### ISSUE THREAD

**Issue by kiwisincebirth** [wwarthen/RomWBW#427]
Just found an issue (assume it might be known) with assigning high slice numbers in hd512. 

SD0 (disk2) - is 8GB media with a 512MB RomWBW partition (hd1k)

```
Capacity of disk 2:  ( 15G)  31116288      Geom dacc1010
Nr  ---Type- A --      Start         End   LBA start  LBA count  Size
 1    RomWBW   2e      8:0:1  1023:15:16        2048    1048576  512M
 2 FAT32 lba   0c   1023:0:1  1023:15:16     1050624   15564800    7G
```

SD1 (disk3) - is 8BG media with FAT 384mb FAT partition (hd512) - this is actually imaged from a hd512_combo.img file

```
Capacity of disk 3:  ( 15G)  31116288      Geom dacc1010
Nr  ---Type- A --      Start         End   LBA start  LBA count  Size
 1             00       *** empty ***
 2     FAT16   06   1023:0:1  1023:15:16     1064960     786432  384M
```

So when I assign and try and use these

```
D>assign l:=sd0:255

   L:=SD0:255

   901 Disk Buffer Bytes Free

D>l:
ZSDOS error on L: No Drive
Call: 14

D>assign l:=sd1:255

   L:=SD1:255

   901 Disk Buffer Bytes Free

D>l:   << This is an issue since the drive is logged? without error >>
L>d:
```

... CBIOS correctly generates an error with hd1k Slice 255, since this exceeds the space in the $2E partition, 

But for but for SD1 (hd512) no such issue is generated, it just switches to the L: drive without error, any writes to the L: drive have potential to overwrite a valid partition.

I believe this wouldn't be hard to fix. For Hd512 - We just need to do the size comparison with the LBA start of the FAT partition (or any partition), instead of the total media size in CBIOS as it does now.

A second issue is the ASSIGN.COM is not doing any validation, which would probably require the duplication of logic in 2 places. I am not a fan of duplication, it is probably better to get the logic right in one place (CBIOS) first.

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

> But for but for SD1 (hd512) no such issue is generated, it just switches to the L: drive without error, any writes to the L: drive have potential to overwrite a valid partition.

Yes, under hd512 there is no partition table entry that defines the size of the space to use for RomWBW.

> I believe this wouldn't be hard to fix. For Hd512 - We just need to do the size comparison with the LBA start of the FAT partition (or any partition), instead of the total media size in CBIOS as it does now.

I suppose so, but the code would need to go in a place that impacts CP/M TPA.  I have already been criticized for reducing TPA space to handle the scenarios that I currently do.  I would like people to move to the hd1k format which handles this well.  If you want to take a stab at adding this check for hd512, I am open to it.  Just make sure you add the check to both the CP/M 2.2 CBIOS and the CP/M 3 CBIOS.  Additionally, make sure it is done conditionally so that the TPA impact can be avoided unless this check is desired.

> A second issue is the ASSIGN.COM is not doing any validation, which would probably require the duplication of logic in 2 places. I am not a fan of duplication, it is probably better to get the logic right in one place (CBIOS) first.

ASSIGN.COM intentionally does not do this validation.  I admit it is a deficiency, but the reason has to do with the ability of RomWBW to handle dynamic disk swapping.  Keep in mind that the ASSIGNments do not "stick" to the specific media.  The validation done by ASSIGN would be wrong after a disk swap.  I took the approach of allowing ASSIGN to do what it wants, but validate the access at the time I know for sure what disk media I am actually dealing with.

I freely admit this is a debatable design decision.  There are a couple ways it could be addressed:

- You could make ASSIGN interrogate the current media at the time of an ASSIGNment and do the validation.  However, you would also need to delete all existing ASSIGNments at the time of a disk swap and the user would need to redo their assignments each time.
- You could make ASSIGN persist it's assignments on the physical media.  However, if a disk swap occurs, you would need to do something to resolve conflicting assignments.

I personally feel that these alternatives are more confusing and more complicated than the current solution.  I'm sure some people will disagree 🙂

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
Thanks for your feedback.

>> the code would need to go in a place that impacts CP/M TPA. I have already been criticized for reducing TPA space to handle the scenarios that I currently do. 

I can understand the motivation for not reducing TPA, personally not sure how a few 10's of bytes would make all that much difference. If as you suggested make to inclusion of additional code optional had you considered

* Making hd512 support itself optional. Optionally removing its support, and any validation could save bytes
* Making all slice validation optional, including hd1k, and any ne hd512 that gets added. 

>> ASSIGN.COM intentionally does not do this validation. I admit it is a deficiency, but the reason has to do with the ability of RomWBW to handle dynamic disk swapping

Given the current approach I can see your reasoning, it does make sense. 

However in modern os. removing CF/USB/SD would result in any volumes being unmounted.  And pulling a drive the the computer just booted from (C:) is clearly not supported. Thus my assumption was the hard disks were treated as non-removable media. If this were the case things might be simpler. I am fairly sure this isn't going to change anytime soon.

However the "User Guide" now makes an incorrect statement, that I added. Search for "removable media" in the guide and you will find it.

I will look at adding some code, may take a little time to get to it

Mark

PS. The reason I raised this Issue is : I am working on a CP/M tool that allows slices to be copied in their entirety using hbios to do a sector level copy. Its mostly finished, tested for hd1k hd512 on SD. I just received a CF module and media, so would like to test it on CF as well.

**Comment by wwarthen** [comment]
> I can understand the motivation for not reducing TPA, personally not sure how a few 10's of bytes would make all that much difference. If as you suggested make to inclusion of additional code optional had you considered
> 
> * Making hd512 support itself optional. Removing its support, and any validation could save some bytes
> * Making all slice validation optional, including hd1k, and any hd512 that gets added. Why should hd1k get special treatment.

These are both valid points and not terribly hard to implement by putting conditionals in the build.  The biggest problem is that these changes are in the CBIOS components of CP/M 2.2 and CP/M 3.  Using alternate versions of these would require a user install different variants of the CBIOS for any bootable disk as desired.  Entirely possible, but this is an area that few users seem comfortable with.  I am not personally motivated to pursue this, but happy for you to consider it.

> > ASSIGN.COM intentionally does not do this validation. I admit it is a deficiency, but the reason has to do with the ability of RomWBW to handle dynamic disk swapping
> 
> Given the current approach I can see your reasoning, it does make sense.
> 
> My assumption was the hard disks were treated as non-removable media, probably because to the association of booting to hard drive, in a modern sense the C: drive (what you boot to) has always been considered fixed. In my situation I don't see any reason to swap the media, I might remove it temporarily (FAT access on PC) and put it back, but swapping it would be low frequency and necessitate a reboot. e.g. CP/M -> Fusix

I have occasionally considered removing the ability to support removable hard disks.

> Note the "User Guide" now makes an incorrect statement, that I added. Search for "removable media" in the guide and you will find it.

I think I see what you are refering to and will correct it.

> I will look at adding some code, may take a little time to get to it

Sounds good.

> PS. The reason I raised this Issue is : I am working on a CP/M tool that allows slices to be copied in their entirety using HBIOS to do a sector level copy. Its mostly finished, tested for hd1k hd512 on SD. I just received a CF module and media, so would like to test it on CF as well.

That would be useful.  It has been requested in the past.  How well is it performing?  I would expect it to be a little slow.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
Hi Wayne

> That would be useful. It has been requested in the past. How well is it performing? I would expect it to be a little slow.

Performance varies significantly on the media, being used. Tested on a SC126 - Z180 at 18Mhz. I assume these numbers  woulds basically halve on a Z80 at 8/10 Mhz. 

* Compact Flash Media - about 340 kBytes / sec
* SD card - 24 kBytes / sec

I did consider performance, so the program reads the the CP/M filesystem and finds the highest allocated (4k) block number, and stops copying after this is reached. 

The biggest slice I have to test with is "NZCOM ZCPR 3.4 Operating System" (combo image). On CF media (very glad I just installed it today), it is quite fast.

```
Found 279 directory entries, with 697 (4k) extents.
Copying data blocks. .........................
Copied 2816 kBytes in 7 seconds.
```

Mark.

**Comment by wwarthen** [comment]
That is pretty reasonable performance.  CF Media on an 18 MHz system is probably a best case scenario, but 7 seconds is not bad.  Good idea using the filesystems highest allocated block to limit the data copied.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
Hi Wayne.

I am thinking of addressing the reported issue by adding a new function to HBIOS ( see below )

Advantages
* Can remove this code from CBIOS reducing it overall size, about 0x100 bytes
* It puts the code in a shared location reusable by CBIOS, CPM3BIOS, and any other tools, e.g. CopySL, or Assign.com (if thats a direction you want to go in future)
* Closes the loop on a issue reported recently #415, as an API is now available to discover the true MEDIA_ID
Disadvantages
* Wont help for UNA BIOS, any existing code will need to remain in CBIOS/CPM3BIOS
* Might create confusion with the "0x18 - DIOMEDIA" function. Why are there 2 similar functions.

Welcome your thoughts ?

Mark.

PS. Thanks for including CopySL. Looks good

```
;
; GET DISK EXTENDED HARD DISK MEDIA INFORMATION
;   This function is intended for Hard Drives, it will scan partition
;   and return Slice LBA offset and hd1k (MID_HDNEW), or hd512 (MID_HD)
;   If the slice number is invalid (wont fit) Staus will return an error
;
;   ENTRY:
;     B: FUNCTION       0xF8   SYSGET
;     C: SUB FUNCTION   0x12   DIOMED
;     D: DISK UNIT, preferably for a hard disk.
;     E: SLICE, ignored if media is not a hard disk
;   RETURNS:
;     A: STATUS, -6 (parameter out of range) - if Slice invalid
;     C: MEDIAID, including MID_HDNEW if hd1k partition is found
;     DEHL: LBAOFFSET, of Slice if found, 0 otherwise.
;
SYS_GETDIOMED:
	; todo
	RET
```

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

Sorry for the delay.  Today was completely taken up with a personal commitment.  I will provide a response tomorrow.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
FYI : Have written and mostly tested the function takes just over 300 bytes of HBIOS space (with functional improvements), over CBIOS which was about 250 bytes

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

I am a big fan of freeing up 250 bytes of CBIOS space. 😀

The only issue I have is that I am reluctant to put CP/M specific code in HBIOS.  The architcture of HBIOS is that it be OS agnostic (similar to the BIOS in an IBM PC).  The concept of slices is CP/M specific.

My preference would be to locate your code in the HBIOS AUX bank.  I have had the idea of relocating much of the CBIOS code into the AUX bank for a while, but never had the time to work on it.  The idea is that the code be imbedded in the CBIOS in the disk buffer area.  When CBIOS is launched, it would copy this code to the AUX bank and free up the buffer space.  As needed, CBIOS would make an inter-bank call which is very similar to invoking an HBIOS function.

In addition to preserving the HBIOS architecture, this approach has some other benefits:

- The CBIOS helper code would be loaded with the CBIOS image so it would be guaranteed to match the running CBIOS.
- Provides an extensibe infrastructure that allows moving other CBIOS helper functions out of space constrained upper RAM.
- Not only would this free up the CBIOS space, it would avoid any impact to HBIOS bank memory usage.
- It would address both of the issues you mentioned
  - Could be UNA compatible
  - Would eliminate any API confusion about the functions in HBIOS.

The negative to this is the extra work of course.  Since this mechanism of relocating some of CBIOS to the AUX bank at startup is not currently in place, this would take some extra work.  However, once in place, it could be leveraged to add more helper functions that would further reduce CBIOS memory usage.

Note that this is the way that CP/M 3 already works.  In fact, in the case of CP/M 3, your enhanced code would just go right into the AUX bank which CP/M 3 already uses for much of its code.

I think this approach would allow the code you developed to be used.  It would just require the work to run it from the AUX bank.  Let me know what you think.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
HI Wayne

> The only issue I have is that I am reluctant to put CP/M specific code in HBIOS. The architcture of HBIOS is that it be OS agnostic (similar to the BIOS in an IBM PC). The concept of slices is CP/M specific.

Completely understand this point of view, keeping code in correct hierarchical partitions, makes perfect sense to me.  FYI : I have also observed similar code in romldr.asm (startup command processor) - when you type "2.10" it needs to compute the location (sector) to load the OS boot sectors from before transferring control to the OS. 

I am assuming the slice number only makes sense for CPM, other OS's only require the Unit number. Looking at fuzix (limited knowledge) it works more like a modern OS, the boot sectors are at the start of the disk. and they allow you to them boot the OS from an (fdisk) partition

A slight edge case is that once a RomWBW partition is detected, it is only possible to boot into a slice of that partition. If there we also fusix partitions on the same disk, these could NOT be booted. Slice 0 means Slice 0 of the RomWBW partition, not Sector 0 of the disk - as I said an edge case.

I guess my point is RomWBW does have to know about the CPM Slice layout strategy (to boot it). This is not the case for Fuzix, I just boots off Sector 0 regardless. The fuzix boot loader deals with partition table. 

 - Just Food for thought

> My preference would be to locate your code in the HBIOS AUX bank. I have had the idea of relocating much of the CBIOS code into the AUX bank for a while, but never had the time to work on it

I am assuming you are referring to ( BID_AUX 0x8D OS Code Bank ), not BID_BIOS. Which makes sense for CPM 2.2 I would guess this means is not being used, since CPM 2.2 is not a banked OS. For CPM 3.0 (banked) BID_AUX would be occupied by the OS itself, and CBOS may not be able to use it.

> The negative to this is the extra work of course. Since this mechanism of relocating some of CBIOS to the AUX bank at startup is not currently in place, this would take some extra work. 

FYI: I don't think I could help out here, this is fairly fundamental.

> I think this approach would allow the code you developed to be used. It would just require the work to run it from the AUX bank. Let me know what you think.

I am happy to adopt any guidelines you put in place. In principle I dont have any issue. Only one caveat is the function I wrote makes HBIOS called - currently via a call to "DIO_DISPATCH" - if the function moves to AUX bank this would need to be via RST 8 (or CALL HB_INVOKE) - and require interbank buffer transfer (partition table sector)

Mark

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

You make a really good point about the existing slice "awareness" in the ROM.  I remember realizing that long ago and did make a conscious effort to isolate this issue to romldr.  In my defense, I had intended to move the slice stuff into boot sector code eventually.  Honestly, it has never become a priority and has never really caused an issue.

After thinking about romldr, I realize that (for now) it would benefit romldr as well as CBIOS to have the function you propose in HBIOS.  I like reducing redundant code.  Your solution is straightforward and useful.

So, I think I have come around to agreeing with you and I am OK with getting a pull request from you to introduce this new function in HBIOS.  There are 3 existing places where this function should then be leveraged: CP/M 2.2 CBIOS, romldr, and CP/M 3 CBIOS.  Those changes are not hard.  If you want to take a shot at them, great.  Otherwise, I will pursue it.

My only caveat is that someday I may refactor this stuff completely.  That day may never come, but I just wanted you to know it is possible.

Thank you, Wayne

**Comment by kiwisincebirth** [comment]
Hi Wayne, 

Thanks for considering my feedback, as I might of said before happy to take your decisions. But it does mean I can contribute these changes, and of course future refactoring is always going to happen, no issues there.

If you don't mind it would be beneficial to do smaller PRs, first off introduce the hbios function then seperate pr's for cbios, romldr etc. I am more a believer of smaller incremental changes, less risk imho.

Mark

**Comment by wwarthen** [comment]
Strongly agree.  Introduce these changes incrementally.

Thank you, Wayne

**Comment by wwarthen** [comment]
RomWBW Development Snapshot v3.5.0-dev.88 has been posted with these changes.

Thanks! Wayne

**Comment by kiwisincebirth** [comment]
Hi : @wwarthen 

See next PR  #431 It raises an important Question: When booting a Floppy (non High Capacity) the HBIOS function ignores the Slice Number. Consequently, a user could choose to boot from "2.100" (2 is a floppy), and it would just boot (I dont have floppy to specifically test this), as the HBIOS function returns Sector Offset = 0.  Should HBIOS function be more restrictive and enforce Slice = 0 for floppy media, so typing "2.100" would raise a Slice not Valid error ?

Secondly. I have been looking through CBIOS, and the setting/reseting of the LBA Flag (Bit 7 - MSB of LBA offset), If you search for "SEKLBA", or ",7" in CBIOS you will see several (approx 5) examples of SET RES of this bit. The issue I have is the setting/resetting of this flag seems to be mixed between tiers of the code, and it is a bit confusing as to the overall intent. 

I am trying to understand the intent.
* In romldr.asm it only ever sets it (once), just before calling BF_DIOSEEK in the "diskread" function. For the UNA bios, the flag is never set, which leads me to believe it only applies to only to HBIOS function calls ?
* I am assuming the variable (SEKLBA) is ultimately copied (HSTLBA), since the main "DSK_IO:" routines deal with HSTxxx variables exclusively?
* In "DSK_IO:" the bit is tested (only for RomWBW) to determine how to compute CHS address to pass to DIOSEEK, but for UNA it simply clears the bit before its BIOS call. Which further confirms Bit 7 is only for RomWBW ?
* This also leads me to believe that Bit7 of (SEKLBA+3) only needs to be set for Non HD media for HBIOS ?

Mark.

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

> See next PR #431 It raises an important Question: When booting a Floppy (non High Capacity) the HBIOS function ignores the Slice Number. Consequently, a user could choose to boot from "2.100" (2 is a floppy), and it would just boot (I dont have floppy to specifically test this), as the HBIOS function returns Sector Offset = 0. Should HBIOS function be more restrictive and enforce Slice = 0 for floppy media, so typing "2.100" would raise a Slice not Valid error ?

Yes, I think it would be best if it returned an error if a non-zero slice was specified for media that is not "slice capable".

> Secondly. I have been looking through CBIOS, and the setting/reseting of the LBA Flag (Bit 7 - MSB of LBA offset), If you search for "SEKLBA", or ",7" in CBIOS you will see several (approx 5) examples of SET RES of this bit. The issue I have is the setting/resetting of this flag seems to be mixed between tiers of the code, and it is a bit confusing as to the overall intent.
> 
> I am trying to understand the intent.

The intent of the bit is to inform the HBIOS SEEK function whether the field currently represents a CHS value or an LBA value since it supports either.  The bit is set to signify an LBA value.  At the time, I thought it was better than using two separate seek calls in the API.  The concept is borrowed from the ATA interface which also uses the high bit to signify an LBA vs CHS value.  It essentially just overloads the seek function.

Not sure if I like how it has worked out though.  In romldr, it is pretty clean.  However, in CBIOS, there are places where I need to manipulate the bit.  Reasons for this include UNA support and removing the bit during computations.

> * In romldr.asm it only ever sets it (once), just before calling BF_DIOSEEK in the "diskread" function. For the UNA bios, the flag is never set, which leads me to believe it only applies to only to HBIOS function calls ?

Yes, the high bit is only valid for RomWBW.  UNA does not support floppy drives and has no CHS support and does not use this bit per its API.

> * I am assuming the variable (SEKLBA) is ultimately copied (HSTLBA), since the main "DSK_IO:" routines deal with HSTxxx variables exclusively?

That's right.

> * In "DSK_IO:" the bit is tested (only for RomWBW) to determine how to compute CHS address to pass to DIOSEEK, but for UNA it simply clears the bit before its BIOS call. Which further confirms Bit 7 is only for RomWBW ?

Correct.

> * This also leads me to believe that Bit7 of (SEKLBA+3) only needs to be set for Non HD media for HBIOS ?

It should be cleared for non-HD media.  In the case of HD media, RomWBW supports either CHS or LBA access.  Internally, RomWBW converts all HD access to LBA.  However, you can call the HBIOS SEEK function with either a CHS or LBA value.  It it is called with a CHS value, HBIOS will convert it to an LBA value before the physical access.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
@wwarthen 

Some more questions. on CPM 3 specifically. 

There appear to be 2 places where the MBR/Partition is scanned "cpm33/diskio.z80", and "cpm3/biosldr.z80", and both appear to have identical code. While i am fairly comfortable with the function of diskio - following what cbios does, I am not entirely sure about biosldr. What does biosldr (boot function) do, it appear to replicate romldr.asm. Can you provide advice of the function of biosldr and what need to occur here?

Also I don't see any references to UNA BIOS in this code. Can I assume that CPM3 is not supporting of UNA BIOS ?

**Comment by wwarthen** [comment]
Hi @kiwisincebirth,

Good question.  CP/M 3 loads differently than CP/M 2.  The entire CP/M 2 OS is loaded directly from the system tracks of the boot disk.  The CP/M 3 OS is actually loaded from the CP/M filesystem of the boot disk (file called CPM3.SYS).  In order to do this, a small loader application is installed on the system tracks of the boot disk.  This loader application has just enough functionality to read a CP/M filesystem, locate CPM3.SYS, load it, and launch it.

In order to implement this two-phase loader in CP/M 3, the disk I/O routines of the full OS must be duplicated in the loader (including slice awarenewss).  That is what you are seeing.  I always intended to go back and try to find a way to share as much as possible of the disk I/O code between the biosldr and diskio.  Since both the loader and the full OS are built with object modules that are linked together, it should be possible to refactor some/all of the disk I/O code into a common module.  I just have not taken the time to work on it.  The new HBIOS slice location function actually achieves a lot of this goal.

Regarding UNA, you are correct, there is no support for UNA in the RomWBW CP/M 3 adaptation.

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
@wwarthen - RE The new HBIOS function : I was gong to suggest maybe renaming the function. Putting it inside SYSGET 0xF8 is sort of hiding/ normalising it. It was just my first guess as to were it should reside. I am suggesting something like 

* Creating a new 0xFF Extended System Function that it sits inside as a sub-function (or)
* Higher level it sit as a top level function 0xE0 - Where 0xE* - is a group of "E", "EXT" Extended or Extension function(s)

The point is to call it out for what it is, and document this fact. It will be easier now to make this change, as when (not a question anymore) it gets adopted it would be harder to change.

**Comment by wwarthen** [comment]
@kiwisincebirth

Yeah, that idea had occurred to me as well.  I was on the fence about it.  Indeed, it is more aptly considered a helper function as opposed to a system function.

I think I like the idea of implementing a new top level function group for such helper (extension) functions.  I agree that doing so would help other users understand what this function(s) are.  0xE0-0xEF makes sense.

Let me know if you want me to add the high-level dispatching for this, but you are free to do it yourself.  It is not hard and just follows the same technique as the SYS function group.

Thanks, Wayne

Thanks, Wayne

**Comment by kiwisincebirth** [comment]
@wwarthen After last PR - I am thinking this issue should be closed.
