### ISSUE TITLE
The default 1Mb rom build for the SBC does not fit all files

### ISSUE THREAD

**Issue by b1ackmai1er** [wwarthen/RomWBW#43]
Using command line: build sbc std 1024

cannot write: inttest.com, cpm.sys, zsys.sys

I checked if xmuf.com was the culprit but appears not to be.

I'm assuming the default build should fit all files, so maybe something needs to be removed.

Apologies in advance if it is something I have cause or missed :)

Regards Phil.

**Comment by wwarthen** [comment]
It looks like I caused this problem when I added FAT.COM to the 1MB ROM disk image.  I need to review the contents of the 1MB ROM disk and trim the contents to fit.  I will do this in a few days.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Confirmed that the addition of FAT.COM to the 1MB ROM disk image caused the overflow.  Rather than remove the very useful FAT.COM, I have instead removed WSCHHELP.OVR -- this is the help file for the WSCHANGE program, so it is of marginal value.  In truth, Wordstar itself is probably not really a good idea on the ROM disk image (since it is on the hard disk image).  For now, just removing WSCHHELP.OVR will suffice.
