### ISSUE TITLE
Creating custom build for TMS9918 on RC2014

### ISSUE THREAD

**Issue by vipoo** [wwarthen/RomWBW#97]
Hi Ya,

Not sure if this is the best place, or would it be perferred to post on the RC2014 google group?

Tonight i was playing around trying to get the RomWBW build to include the TMS9918 VDU driver, for my RC2014 build.

I added the following to the RCZ80_std config:
```
TMSENABLE .SET  TRUE   ; TMS: ENABLE TMS9918 VIDEO/KBD DRIVER (TMS.ASM)
TMSMODE   .EQU  TMSMODE_RC2014
```

In tms.ams, I added:
```
#IF (TMSMODE == TMSMODE_RC2014)
TMS_DATREG	.EQU	$BE		; READ/WRITE DATA
TMS_CMDREG	.EQU	$BF		; READ STATUS / WRITE REG SEL
TMS_PPIA	.EQU	0		; PPI PORT A
TMS_PPIB	.EQU	0		; PPI PORT B
TMS_PPIC	.EQU	0		; PPI PORT C
TMS_PPIX	.EQU	0		; PPI CONTROL PORT
#ENDIF
```

I assume the TMS_PPIx are for keyboard and not relevant for what i am trying to do.

I just used the rcz80_std.com version to test it out - and i notice that my video display now has a flashing cursor.  

But when i tried to call the HBIOS function to write a char - I just get a panic -- and i have no idea how to debug this.

The code I tried was:

```
LD B, 47H
LD E, 67
LD C, 40H ; tried lots of things here - do not understand whats required here
RST 08
```

I am trying to do something that will not work - Am i completly misunderstanding this?
What value is required for C?
And in general, how might i debug/diagnose this?

And if you got this far - thanks for ready my question.
Dean

**Comment by wwarthen** [comment]
Hi Dean,

Well, you are in new territory.  While the TMS9918 driver works, it has only ever been utilized for the ECB bus systems.  Never on RC2014 bus systems.  With that said, it would be very cool to get it working!  See my comments below.

-Wayne

> Not sure if this is the best place, or would it be perferred to post on the RC2014 google group?

I guess this is fine for now.  If we run into questions about the RC2014 TMS9918 module, we may need to use the newsgroup instead.

> Tonight i was playing around trying to get the RomWBW build to include the TMS9918 VDU driver, for my RC2014 build.
> 
> I added the following to the RCZ80_std config:
> 
> ```
> TMSENABLE .SET  TRUE   ; TMS: ENABLE TMS9918 VIDEO/KBD DRIVER (TMS.ASM)
> TMSMODE   .EQU  TMSMODE_RC2014

Looks good.

> ```
> 
> In tms.ams, I added:
> 
> ```
> #IF (TMSMODE == TMSMODE_RC2014)
> TMS_DATREG	.EQU	$BE		; READ/WRITE DATA
> TMS_CMDREG	.EQU	$BF		; READ STATUS / WRITE REG SEL
> TMS_PPIA	.EQU	0		; PPI PORT A
> TMS_PPIB	.EQU	0		; PPI PORT B
> TMS_PPIC	.EQU	0		; PPI PORT C
> TMS_PPIX	.EQU	0		; PPI CONTROL PORT
> #ENDIF
> ```

Also looks good as long as the values for TMS_DATAREG and TMS_CMDREG are right.

> I assume the TMS_PPIx are for keyboard and not relevant for what i am trying to do.

Correct. 

> I just used the rcz80_std.com version to test it out - and i notice that my video display now has a flashing cursor.

That is a very good sign.  A lot must work right to get that far!

> But when i tried to call the HBIOS function to write a char - I just get a panic -- and i have no idea how to debug this.
> 
> The code I tried was:
> 
> ```
> LD B, 47H
> LD E, 67
> LD C, 40H ; tried lots of things here - do not understand whats required here
> RST 08
> ```

The API is not well documented for this.  The value for B and E look fine.  The value for C will need to be Video Unit number for the TMS adapter displayed at boot.  At boot, you should see a line something like this:

`Video 0     TMS0:       CRT               Text 40x25, TTY`

In the above example, the TMS video unit is 0 and you would put 0 in the C register for the call.

> I am trying to do something that will not work - Am i completly misunderstanding this?

Since the hardware is totally untested for RomWBW, it is hard to say if it will work.  But, since you got a cursor, maybe...

> What value is required for C?

Answered above.

> And in general, how might i debug/diagnose this?

There are no simple rules for doing this.  Start by using the right value for C and let me know what happens.

> And if you got this far - thanks for ready my question.
> Dean

**Comment by vipoo** [comment]
Thanks Wayne ... I will give it another go soon.

**Comment by wwarthen** [comment]
Hi Dean,

In the process of updating documentation for the next full release of RomWBW, I found that there were some errors in the VDA functions documentation in the RomWBW Architecture document.  It looks like you were using function $47 to output a character (because that is what the document indicated).  I sincerely apologize, but the documentation was wrong on this function call.  Function $48 should be used to output a character.  The RomWBW Architecture document has been updated.  Note that several of the VDA function numbers were "off", so you should double-check any that you are trying to use.

I am interested to hear how you are doing with this effort.  Since you already got a blinking cursor, I believe that the RC2014 TMS9918 module should be basically compatible with RomWBW already.

Thanks,

Wayne

**Comment by dnetherton** [comment]
Hi Wayne,

That explains why i was not able to get anywhere with the BDOS command - cool - i will give it a go.

But I had managed to get CPM to use the CRT mode.  With the VDU enabled, I was able to use the cpm `stat` command to direct output to the screen.  I had to hack some code, to make it use the serial input for keyboard (not really sure how all this is meant to work...) -- I was able to use CPM in 40 column text output on the video.  CPM in 40 columns and 24 lines is not very practical - but its cool - and its certainly very retro.

I will get back to you in regards to using the BDOS command directly.

Dean

**Comment by wwarthen** [comment]
Thanks Dean.

Sounds like it is generally functional, just lacking a good way to deal with keyboard input.

At a minimum, I can create an official variant of the TMS driver that nulls out the keyboard input.  Still not terribly useful.  Problem is that RomWBW sort of expects that physical display devices are paired with dedicated physical input devices.  Up until now, that has been true.  I will need to think about this a bit.

Would be cool if there was a RC2014 partner module that simply provided a PS/2 or USB keyboard interface...

-Wayne

**Comment by feilipu** [comment]
Actually, there is already a RC2014 standard module that fully supports a keyboard option. It is Ed Brindley's 82C55 PPI module, as now sold by Spencer.

When Ed designed this board he [thought ahead and provided jumpers](https://github.com/electrified/rc2014-82c55-ide/blob/master/README.md#jp1---jp4) to ensure that it was possible to rearrange the inverters in the Port C control lines so that the board was actually able to be a fully functional parallel interface platform.

The 82C55 data sheet shows how it can be used as a fully decoded keyboard input.

![82c55_keyboard](https://user-images.githubusercontent.com/3955592/76710943-9fdf7f80-675f-11ea-95fb-ea7d7178fb08.png)

The challenge remaining @dnetherton  (should you choose to accept it) is to wire up the keys on a PCB and write a keyboard scanner. 👍

**Comment by vipoo** [comment]
Hmmm -- interesting --- Challenge accepted - but it just might take a
while.... I do have some keyboard bits coming from china - (kbdfans) - but
its been very delayed....

**Comment by vipoo** [comment]
And additional - I really dont feel like i know what i am doing - i just
keep poking at stuff until something works - never fully understanding
why... 😕

**Comment by vipoo** [comment]
Hi Wayne,

Just managed to get a single character displayed thru the HBIOS call ... little steps...

**Comment by wwarthen** [comment]
Great!  Apparently it helps to have the documentation be correct!  So sorry about that.

**Comment by wwarthen** [comment]
I have built and tested a J.B. Lang TMS9918 board on RC2014.  Minor tweaks to config files have been committed.  Using MSX port stardards.  Everything checks out.

Closing this issue, but feel free to resubmit if there are any remaining issues.
